"""Response-adaptive motion-program components.

RAMP deliberately lives outside :mod:`scene2motion.program`: the latter is the frozen 43-D
audit representation used by historical checkpoints and ledgers.  New event-aligned packet
representations can evolve here without changing those artifacts' meaning.
"""

from .packet import (
    CoherentPacketPair,
    CoherentMotionPacket,
    MAX_PACKET_STRENGTH,
    PACKET_SCHEMA_VERSION,
    PHASE_MATCH_SCHEMA_VERSION,
    TARGET_PHASE_MATCH_SCHEMA_VERSION,
    PacketControls,
    PacketRenderInfo,
    PhaseMatch,
    SO3_BRANCH_MARGIN_RAD,
    constraint_support_digest,
    extract_absolute_packet,
    extract_packet_pair,
    extract_residual_packet,
    render_packet,
)
from .phase import (
    PHASE_ALIGNMENT_METHOD,
    TARGET_PHASE_ALIGNMENT_METHOD,
    StanceEvidence,
    TargetPhaseMatch,
    align_cyclic_phase_windows,
    align_target_phase_window,
)
from .phase_observability import (
    PHASE_BACKGROUND_METHOD,
    PHASE_BASELINE_FRAMES,
    PHASE_BASELINE_SUPPORT_METHOD,
    PHASE_OBSERVABILITY_SCHEMA_VERSION,
    PHASE_PROMINENCE_METHOD,
    PhaseBackgroundContrast,
    PhaseObservabilityEvidence,
    PhaseProminenceReceipt,
    enumerate_background_phase_contrasts,
    enumerate_phase_prominences,
    measure_phase_observability,
    phase_observability_measurement_hash,
)
from .route_phase import (
    ROUTE_DERIVATIVE_CONVENTION,
    ROUTE_GEOMETRY_CONVENTION,
    ROUTE_PROGRESS_METHOD,
    ROUTE_PROGRESS_SCHEMA_VERSION,
    ROUTE_PROGRESS_SLOPE_POLICY,
    RouteProgressProgram,
    RouteTimingBounds,
    reparameterize_route_progress,
    route_progress_selection_key,
)
from .step_phase import (
    COMMON_STEP_PHASE_PROTOCOL_VERSION,
    STEP_PHASE_METHOD,
    STEP_PHASE_PROTOCOL_VERSION,
    StepPhaseCycle,
    StepPhaseLandmarks,
    align_step_phase_cycles,
    align_step_target_phase,
    enumerate_step_phase_cycles,
    enumerate_step_phase_cycles_from_qpos,
    step_phase_cycle_from_qpos,
    step_phase_common_physical_protocol_hash,
    step_phase_measurement_protocol_hash,
    validate_step_phase_cycle,
)

__all__ = [
    "CoherentPacketPair",
    "CoherentMotionPacket",
    "MAX_PACKET_STRENGTH",
    "PACKET_SCHEMA_VERSION",
    "PHASE_MATCH_SCHEMA_VERSION",
    "PacketControls",
    "PacketRenderInfo",
    "PHASE_BACKGROUND_METHOD",
    "PHASE_BASELINE_FRAMES",
    "PHASE_BASELINE_SUPPORT_METHOD",
    "PHASE_OBSERVABILITY_SCHEMA_VERSION",
    "PHASE_ALIGNMENT_METHOD",
    "PHASE_PROMINENCE_METHOD",
    "ROUTE_PROGRESS_METHOD",
    "ROUTE_DERIVATIVE_CONVENTION",
    "ROUTE_GEOMETRY_CONVENTION",
    "ROUTE_PROGRESS_SCHEMA_VERSION",
    "ROUTE_PROGRESS_SLOPE_POLICY",
    "TARGET_PHASE_ALIGNMENT_METHOD",
    "TARGET_PHASE_MATCH_SCHEMA_VERSION",
    "PhaseMatch",
    "PhaseBackgroundContrast",
    "PhaseObservabilityEvidence",
    "PhaseProminenceReceipt",
    "RouteProgressProgram",
    "RouteTimingBounds",
    "SO3_BRANCH_MARGIN_RAD",
    "STEP_PHASE_METHOD",
    "STEP_PHASE_PROTOCOL_VERSION",
    "COMMON_STEP_PHASE_PROTOCOL_VERSION",
    "StepPhaseCycle",
    "StepPhaseLandmarks",
    "constraint_support_digest",
    "StanceEvidence",
    "TargetPhaseMatch",
    "align_cyclic_phase_windows",
    "align_step_phase_cycles",
    "align_step_target_phase",
    "align_target_phase_window",
    "enumerate_step_phase_cycles",
    "enumerate_step_phase_cycles_from_qpos",
    "enumerate_background_phase_contrasts",
    "enumerate_phase_prominences",
    "extract_absolute_packet",
    "extract_packet_pair",
    "extract_residual_packet",
    "render_packet",
    "measure_phase_observability",
    "phase_observability_measurement_hash",
    "reparameterize_route_progress",
    "route_progress_selection_key",
    "step_phase_cycle_from_qpos",
    "step_phase_common_physical_protocol_hash",
    "step_phase_measurement_protocol_hash",
    "validate_step_phase_cycle",
]
